MAMS/MAMS/Controllers/CropController.cs
using MAMS_Models.Model;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MAMS.Controllers
{
    public class CropController : Controller
    {
        private BOL.CropBOL _objCropBOL;
        public CropController()
        {
            _objCropBOL = new BOL.CropBOL();
        }
        public IActionResult Index()
        {
            List<Crop> crops = _objCropBOL.GetCropInfo();
            return View(crops);
        }

        public IActionResult CropAdd()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CropAdd(Crop crop)
        {
            int affectedRows = 0;
            if (crop != null)
            {
                affectedRows = _objCropBOL.CropAdd(crop);
                if (affectedRows > 0)
                {
                    ModelState.Clear();
                }
            }
            ViewBag.CropAddStatus = affectedRows;
            return View();
        }
        public IActionResult EditCrop(int Id)
        {
            var crop = _objCropBOL.GetSpecificCropInfo(Id);

            return View(crop);
        }
        [HttpPost]
        public IActionResult EditCrop(Crop crop)
        {
            int affectedRows = 0;
            if (crop != null)
            {
                affectedRows = _objCropBOL.EditCrop(crop);
                if (affectedRows > 0)
                {
                    return RedirectToAction("Index");
                }
            }
            ViewBag.CropAddStatus = affectedRows;
            return View();
        }
        [HttpPost]
        public IActionResult DeleteCrop(int cropId)
        {
            int affectedRows = _objCropBOL.DeleteCrop(cropId);
            return Ok(affectedRows);
        }
    }
}

MAMS/MAMS/Views/Crop/CropAdd.cshtml
@model MAMS_Models.Model.Crop
@{ var status = ViewBag.CropAddStatus; }
@{
    ViewData["Title"] = "Add Crop";
}

<script src="~/js/jquery-191-min.js"></script>

<!-- #region    Add Crop Form -->

<div class="card">
    <div class="card-header card-header-primary">
        <h5 class="card-title"><i class="fab fa-canadian-maple-leaf"></i> Add Crop</h5>
    </div>
    <div class="card-body">
        <form enctype="multipart/form-data" asp-action="CropAdd" asp-controller="Crop" method="post">
            <div class="row">
                <div class="col-md-4 col-sm-4">
                    <div class="form-group">
                        <label class="control-label bold">Name</label>
                        <input type="text" asp-for="Name" class="form-control form-control-inline" required>
                    </div>
                </div>
                <div class="col-md-2 col-sm-2">
                    <div class="form-group">
                        <div class="checkbox margin-top-30 ml-10">
                            <label asp-for="Status">
                                <input asp-for="Status" checked />
                                @Html.DisplayNameFor(x => x.Status)
                            </label>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <a type="button" id="btnBack" class="btn btn-success btn-round float-right" asp-controller="Crop" asp-action="Index">
                        <i class="fa fa-arrow-left"></i> Back
                    </a>
                </div>
                <div class="form-group">
                    <button type="submit" id="idAdd" class="btn btn-success btn-round btn-success">
                        <i class="fa fa-plus-circle"></i> Add
                    </button>
                    <div class="clearfix"></div>
                </div>
            </div>
        </form>
    </div>
</div>

<!-- #endregion -->
<!-- #region alert -->

<div id="alertSuccess" data-notify="container" class="col-11 col-md-4 alert alert-success alert-with-icon animated fadeInDown" role="alert" data-notify-position="top-center" style="display: inline-block; margin: 15px auto; position: fixed; transition: all 0.5s ease-in-out 0s; z-index: 1031; top: 20px; left: 0px; right: 0px;">
    <button type="button" aria-hidden="true" class="close" data-notify="dismiss" style="position: absolute; right: 10px; top: 50%; margin-top: -9px; z-index: 1033;">
        <i class="material-icons">close</i>
    </button><i data-notify="icon" class="material-icons">add_alert</i><span data-notify="title"></span> <span data-notify="message"><b>Crop</b> <br>New Crop added successfuly!</span>
    <a href="#" target="_blank" data-notify="url"></a>
</div>
<div id="alertDanger" data-notify="container" class="col-11 col-md-4 alert alert-danger alert-with-icon animated fadeInDown" role="alert" data-notify-position="top-center" style="display: inline-block; margin: 15px auto; position: fixed; transition: all 0.5s ease-in-out 0s; z-index: 1031; top: 20px; left: 0px; right: 0px;">
    <button type="button" aria-hidden="true" class="close" data-notify="dismiss" style="position: absolute; right: 10px; top: 50%; margin-top: -9px; z-index: 1033;">
        <i class="material-icons">close</i>
    </button><i data-notify="icon" class="material-icons">add_alert</i><span data-notify="title"></span> <span data-notify="message"><b>Crop</b> <br>New Crop added not successfuly!</span>
    <a href="#" target="_blank" data-notify="url"></a>
</div>
<!-- #endregion -->
<!-- #region script -->

<script type="text/javascript">
    $("#alertSuccess").hide();
    $("#alertDanger").hide();
    var status = ('@status');
    if (status == "1")
    {
        $("#alertSuccess").show();
        setTimeout(function () {
            $("#alertSuccess").hide();
        }, 3000);
    }
    if (status == "0")
    {
        $("#alertDanger").show();
        setTimeout(function () {
            $("#alertDanger").hide();
        }, 3000);
    }
</script>
<!-- #endregion -->
<!-- #region Style -->
<style>
    input#Name {
        border: 0px;
    }

    .form-group .bmd-label-static {
        top: 0px;
    }

    .checkbox.margin-top-30.ml-10 {
        margin-top: 20px;
    }

    input#Status {
        width: 20px;
        display: inline;
    }

    a#btnBack {
        height: 30px;
        line-height: 1;
    }

    button#idAdd {
        height: 30px !important;
        line-height: 1px !important;
        padding-bottom: 11px;
    }

    i.fa.fa-plus-circle {
        font-size: 16px !important;
    }

    i.fa.fa-arrow-left {
        font-size: 15px !important;
    }
</style>
<!-- #endregion -->

MAMS/MAMS/Views/Crop/EditCrop.cshtml
@model MAMS_Models.Model.Crop
@{ var status = ViewBag.CropAddStatus; }
@{
    ViewData["Title"] = "Edit Crop";
}
<script src="~/js/jquery-191-min.js"></script>

<!-- #region Form Edit Crop -->

<div class="card">
    <div class="card-header card-header-primary">
        <h5 class="card-title"><i class="fab fa-canadian-maple-leaf"></i> Update Crop</h5>
    </div>
    <div class="card-body">
        <form enctype="multipart/form-data" asp-action="EditCrop" asp-controller="Crop" method="post">
            <input type="text" asp-for="UID" class="form-control" style="display:none">
            <div class="row">
                <div class="col-md-4 col-sm-4">
                    <div class="form-group">
                        <label class="control-label bold">Name</label>
                        <input type="text" asp-for="Name" class="form-control form-control-inline" required>
                    </div>
                </div>
                <div class="form-group">
                    <a type="button" id="btnBack" class="btn btn-success btn-round float-right" asp-controller="Crop" asp-action="Index">
                        <i class="fa fa-arrow-left"></i> Back
                    </a>
                </div>
                <div class="form-group">
                    <button type="submit" id="idAdd" class="btn btn-success btn-round btn-success">
                        <i class="fa fa-plus-circle"></i> Update
                    </button>
                    <div class="clearfix"></div>
                </div>
            </div>
        </form>
    </div>
</div>
<!-- #endregion -->

<!-- #region Style -->
<style>
    input#Name {
        border: 0px;
    }

    .form-group .bmd-label-static {
        top: 0px;
    }

    .checkbox.margin-top-30.ml-10 {
        margin-top: 20px;
    }

    input#Status {
        width: 20px;
        display: inline;
    }

    a#btnBack {
        height: 30px;
        line-height: 1;
    }

    button#idAdd {
        height: 30px !important;
        line-height: 1px !important;
        padding-bottom: 11px;
    }

    i.fa.fa-plus-circle {
        font-size: 16px !important;
    }

    i.fa.fa-arrow-left {
        font-size: 15px !important;
    }
</style>
<!-- #endregion -->

MAMS/MAMS/Views/Crop/Index.cshtml
@model List<MAMS_Models.Model.Crop>
@{
    ViewData["Title"] = "Crop";
}
<script src="~/js/ToolTip.js"></script>

<!-- #region Crop Lis --> 
<div class="card ">
    <div class="card-header card-header-primary">
        <h5 class="card-title"><i class="fab fa-pagelines"></i> Crops List</h5>
        @*<p class="card-category">Complete your profile</p>*@
    </div>
    <div class="card-body">
        <a asp-action="CropAdd" asp-controller="Crop" class="btn btn-success btn-circle" style="margin-left: 10px;  font-size: 11px"> <i class="fas fa-leaf"></i> Add Crop</a>
        <div class="table-responsive">
            <table class="table" id="tblDetailList">
                <thead class=" text-primary">
                <th width="3%" tabindex="0" class="bold" aria-controls="tblDetailList" rowspan="1"
                    colspan="1">
                    # &nbsp;
                </th>
                <th width="15%" tabindex="0" class="bold"
                    arial-sort="descending" aria-controls="tblDetailList" rowspan="1" colspan="1">
                    Name
                </th>

                <th width="10%" tabindex="0" class="bold"
                    arial-sort="descending" aria-controls="tblDetailList" rowspan="1" colspan="1">
                    Add Date
                </th>
                <th width="5%" tabindex="0" class="bold"
                    arial-sort="descending" aria-controls="tblDetailList" rowspan="1" colspan="1">
                    Status
                </th>
                <th width="10%" tabindex="0" class="sorting bold" aria-controls="tblDetailList" rowspan="1" colspan="1"> Actions&nbsp;&nbsp;&nbsp;</th>
                </thead>
                <tbody>
                    @{
                        int num = 1;
                    }
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td width="3%" tabindex="0" class="sorting" aria-controls="tblDetailList" rowspan="1" colspan="1"> &nbsp;@num</td>
                            <td width="5%" tabindex="0" class="sorting_1 id" rowspan="1" colspan="1" style="display:none;">@item.UID &nbsp;</td>
                            <td width="5%" tabindex="0" class="sorting_1" aria-controls="tblDetailList" rowspan="1" colspan="1">@item.Name</td>
                            <td width="10%" tabindex="0" class="sorting" aria-controls="tblDetailList" rowspan="1" colspan="1">@item.AddDate</td>
                            <td width="10%" tabindex="0" class="sorting" aria-controls="tblDetailList" rowspan="1" colspan="1">@item.Status</td>
                            <td width="10%" tabindex="0" class="sorting" aria-controls="datatable_orders" rowspan="1" colspan="1">
                                <a asp-action="EditCrop" asp-controller="Crop" asp-route-Id="@item.UID" class=" btn btn-circle btn-sm"><i class="fa fa-edit" data-toggle="tooltip" data-placement="bottom" title="Edit Crop"></i></a>
                                <a class="btn btn-circle btn-sm" name="btnDel" id="@item.UID"><i class="fa fa-trash" data-toggle="tooltip" data-placement="bottom" title="Delete Crop"></i></a>
                            </td>
                        </tr>
                        num++;
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<!-- #endregion -->
<!-- #region Scripts -->
@section Scripts {

    <link href="~/css/confirm.css" rel="stylesheet" />
    <script src="~/js/confirm.js"></script>

}
<!-- #endregion -->
<!-- #region   javascript -->
<script type="text/javascript">
    $(document).ready(function () {
        $('[data-toggle="tooltip"]').tooltip();
        $("#tblDetailList").on('click', "a[name='btnDel']", function () {
            debugger;
            var uId = $.trim($(this).closest('tr').find("td:eq(1)").text());
            $.confirm({
                theme: 'modern',//material modern
                title: 'DELETE!',
                content: 'Are you sure you want to delete Crop?',
                type: 'green',
                typeAnimated: true,
                buttons:
                {
                    tryAgain:
                    {
                        text: 'No',
                        btnClass: 'btn-green',
                    }, warning:
                    {
                        text: 'Yes',
                        btnClass: 'btn-blue',
                        action: function () {
                            debugger;
                            $.ajax({
                                type: "post",
                                url: "/Crop/DeleteCrop",
                                data: { cropId: uId },
                                success: function (data) {
                                    debugger;
                                    if (data == 1) {
                                        location.reload();
                                    }
                                    else {
                                        alert("Crop Delete faild");
                                    }


                                }
                            });
                        }
                    }


                }
            });


        });

    });
</script>
<!-- #endregion -->
<!-- #region Style -->
<style>
    a.btn.btn-circle.btn-sm {
        border: 0px;
        background-color: rgb(204 204 204 / 15%);
        font-size: 10px;
        color: darkgreen;
        padding: 5px
    }
</style>
<!-- #endregion -->